services:
  banked:
    image: bvtc-banked:latest
    container_name: bvtc-banked-container
    build:
      context: ./banked
      dockerfile: Dockerfile
      args:
        GOPROXY: "https://goproxy.cn,direct"
    ports:
      - "8081:8080"
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
      - GOMODCACHE=/go/pkg/mod
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network
    volumes:
      - ./banked/log/logs:/banked/log/logs
      - type: bind
        source: /go/pkg/mod
        target: /go/pkg/mod
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  fronted:
    image: bvtc-fronted:latest
    container_name: bvtc-fronted-container
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      banked:
        condition: service_healthy
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app_network
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
