appName: "bilibili-video-to-netcloud"
log:
  level: "debug"
  path: "/var/log/app.log"
api:
  debug: false
  timeout: 0s # 使用时间单位（如 "30s", "500ms"）
  retry: 0 # 使用整数
  cookie:
    filepath: "./netcloud/data/cookie.json"
    interval: 0s
spew:
  indent: "  "
  maxdepth: 2
  disablemethods: false
  disablepointermethods: true
  continueonmethod: false
  sortkeys: false
